Repository beyond-sw-camp/be08-fin-3Dasoo-SalesBoost-BE, pull requests merged in 2024-11, with the labels that each got.

#174 feat : #173 계약 관련 차트 API 추가
  src/main/java/beyond/samdasoo/contract/controller/ContractController.java
  src/main/java/beyond/samdasoo/contract/service/ContractService.java
Labels: backend, feat

#176 refact : #78 더미데이터 전달
  src/main/resources/base.sql
  src/main/resources/data.sql
Labels: backend, refact

#179 [Chore/#178] deploy job 추가
  .github/workflows/ci-cd.yml
Labels: backend, deploy

#181 [Feat/#180] forecast url 변경
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
Labels: backend, feat, deploy

#182 [Chore/release] 시큐리티 배포 url 추가
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
Labels: backend, chore

#184 [Feat/#122] 영업 예측 api 구현
  src/main/java/beyond/samdasoo/admin/controller/DepartmentController.java
  src/main/java/beyond/samdasoo/admin/dto/DepartmentDto.java
  src/main/java/beyond/samdasoo/admin/service/DepartmentService.java
  src/main/java/beyond/samdasoo/admin/service/DepartmentServiceImpl.java
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
  src/main/java/beyond/samdasoo/common/dto/SearchCond.java
  src/main/java/beyond/samdasoo/common/filter/AuthenticationFilter.java
  src/main/java/beyond/samdasoo/lead/Entity/AwarePath.java
  src/main/java/beyond/samdasoo/lead/controller/LeadController.java
  src/main/java/beyond/samdasoo/lead/dto/AwarePathResponseDto.java
  src/main/java/beyond/samdasoo/lead/dto/LeadSearchCond.java
  src/main/java/beyond/samdasoo/lead/dto/LeadStatusDto.java
  src/main/java/beyond/samdasoo/lead/dto/MonthResponseDto.java
  src/main/java/beyond/samdasoo/lead/dto/SuccessChartDto.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepository.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepositoryCustom.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepositoryImpl.java
  src/main/java/beyond/samdasoo/lead/service/LeadService.java
  src/main/java/beyond/samdasoo/user/dto/LoginUserRes.java
Labels: backend, feat, refact

#186 [Feat/#102] 전사일정 구현
  src/main/java/beyond/samdasoo/companycalendar/controller/CompanyCalendarController.java
  src/main/java/beyond/samdasoo/companycalendar/dto/CompanyCalendarResponseDto.java
  src/main/java/beyond/samdasoo/companycalendar/service/CompanyCalendarService.java
  src/main/java/beyond/samdasoo/plan/dto/PlanRequestDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanResponseDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanUpdateDto.java
  src/main/java/beyond/samdasoo/plan/entity/Plan.java
  src/main/java/beyond/samdasoo/plan/service/PlanService.java
  src/main/resources/base.sql
  src/main/resources/data.sql
Labels: bug, backend, feat

#188 [Feat/#187] 목표 매출 차트 관련 api 구현
  src/main/java/beyond/samdasoo/admin/controller/TargetSaleController.java
  src/main/java/beyond/samdasoo/admin/repository/TargetSaleRepository.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleService.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleServiceImpl.java
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepository.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
Labels: backend, feat

#195 [User/#191] 프로필 사진 업로드
  src/main/java/beyond/samdasoo/contract/entity/Contract.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
  src/main/resources/data.sql
Labels: backend, feat

#196 [Refact/#192] Proposal 제안 등록 시 영업기회 검색 기능
  src/main/java/beyond/samdasoo/lead/dto/LeadSearchCond.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepositoryImpl.java
  src/main/java/beyond/samdasoo/proposal/dto/ProposalRequestDto.java
  src/main/java/beyond/samdasoo/proposal/service/ProposalService.java
Labels: backend, refact

#198 [Feat/#197] 부서 데이터 생성
  src/main/resources/data.sql
Labels: backend, feat, refact

#201 [Fea/#199] 더미 데이터 추가
  src/main/resources/data.sql
Labels: backend, chore

#202 [Feat/#197] 제품 / 프로세스 / 하위 프로세스 데이터 추가
  src/main/resources/base.sql
  src/main/resources/data.sql
Labels: backend, feat

#204 [Chore] 캘린더, 할 일, 일정, 영업활동 데이터
  src/main/resources/base.sql
  src/main/resources/data.sql
Labels: backend, chore

#206 [Feat/#197] 관리자 데이터 수정 및 목표 매출 데이터 추가
  src/main/resources/base.sql
  src/main/resources/data.sql
Labels: backend, feat

#207 [Feat/#183] 매출 계약 관련 엔티티 수정 , 차트 관련 api 생성
  src/main/java/beyond/samdasoo/contract/controller/ContractController.java
  src/main/java/beyond/samdasoo/contract/dto/ContractRequestDto.java
  src/main/java/beyond/samdasoo/contract/dto/ContractResponseDto.java
  src/main/java/beyond/samdasoo/contract/entity/Contract.java
  src/main/java/beyond/samdasoo/estimate/entity/Estimate.java
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/dto/SalesRequestDto.java
  src/main/java/beyond/samdasoo/sales/dto/SalesResponseDto.java
  src/main/java/beyond/samdasoo/sales/entity/Sales.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepository.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
Labels: backend, feat, refact

#208 [Chore/#205] 영업기회 data 추가
  src/main/java/beyond/samdasoo/lead/Entity/Lead.java
  src/main/resources/data.sql
Labels: backend, chore

#211 [Feat/#210] 부서 번호로 영업 사원 조회 api 수정
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/repository/UserRepository.java
  src/main/java/beyond/samdasoo/user/repository/UserRepositoryCustom.java
  src/main/java/beyond/samdasoo/user/repository/UserRepositoryImpl.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
  src/main/resources/base.sql
Labels: backend, feat, refact

#214 [Feat/#183] 계약, 매출 더미데이터 생성
  src/main/resources/data.sql
Labels: backend, feat

#218 [Feat/#212] 견적별 제품 및 견적 데이터 수정 2차
  src/main/resources/data.sql
Labels: backend, feat

#217 [Chore/#215] calendar 관련 데이터 사용자 수정
  src/main/resources/data.sql
Labels: backend, chore

#220 [Feat/#219] Test sales생성 및 기능 구현
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
  src/main/java/beyond/samdasoo/testsales/controller/TestSalesController.java
  src/main/java/beyond/samdasoo/testsales/dto/TestSalesPredictionDto.java
  src/main/java/beyond/samdasoo/testsales/dto/TestSalesRequestDto.java
  src/main/java/beyond/samdasoo/testsales/dto/TestSalesResponseDto.java
  src/main/java/beyond/samdasoo/testsales/dto/TestSalesStatusDto.java
  src/main/java/beyond/samdasoo/testsales/entity/TestSales.java
  src/main/java/beyond/samdasoo/testsales/repository/TestSalesRepository.java
  src/main/java/beyond/samdasoo/testsales/service/TestSalesService.java
  src/main/resources/data.sql
Labels: backend, feat, refact

#221 [Refact/#209] 제안 검색조건 querydsl 설정
  src/main/java/beyond/samdasoo/estimate/repository/EstimateRepositoryImpl.java
  src/main/java/beyond/samdasoo/lead/dto/LeadSearchCond.java
  src/main/java/beyond/samdasoo/proposal/dto/ProposalSearchCriteriaDTO.java
  src/main/java/beyond/samdasoo/proposal/repository/ProposalRepositoryImpl.java
  src/main/resources/base.sql
  src/main/resources/data.sql
Labels: backend, refact

#225 [Feat/#223] 프로세스 삭제 관련 api 수정
  src/main/java/beyond/samdasoo/admin/entity/Process.java
  src/main/java/beyond/samdasoo/admin/entity/SubProcess.java
  src/main/java/beyond/samdasoo/admin/service/ProcessServiceImpl.java
  src/main/java/beyond/samdasoo/admin/service/SubProcessServiceImpl.java
  src/main/resources/data.sql
Labels: backend, feat, refact

#228 [Chore/#209] 리포트 폰트 설정 추가
  .github/workflows/ci-cd.yml
Labels: backend, chore

#230 [Feat/#229] 부서 삭제 관련 api 수정
  src/main/java/beyond/samdasoo/admin/entity/Department.java
  src/main/java/beyond/samdasoo/admin/service/DepartmentServiceImpl.java
  src/main/resources/data.sql
Labels: backend, feat, refact

#231 [Fix / #219 : 에러 부분 체크 ( 계약 , 매출 )
  src/main/java/beyond/samdasoo/contract/entity/Contract.java
  src/main/java/beyond/samdasoo/estimate/entity/Estimate.java
  src/main/java/beyond/samdasoo/sales/entity/Sales.java
Labels: bug, backend, refact

#233 [Feat/#229] 부서 삭제 api 수정
  src/main/java/beyond/samdasoo/admin/service/DepartmentServiceImpl.java
  src/main/java/beyond/samdasoo/admin/service/ProductServiceImpl.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
Labels: backend, feat

#234 [Refact/#209] 고객, 영업기회, 제안 팝업 조회 시 권한 필터 설정
  src/main/java/beyond/samdasoo/admin/repository/SubProcessRepositoryImpl.java
  src/main/java/beyond/samdasoo/customer/dto/SearchCriteriaDTO.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepositoryImpl.java
  src/main/java/beyond/samdasoo/potentialcustomer/repository/PotentialCustomerRepositoryImpl.java
  src/main/java/beyond/samdasoo/proposal/controller/ProposalController.java
  src/main/java/beyond/samdasoo/proposal/dto/ProposalPopResponseDto.java
  src/main/java/beyond/samdasoo/proposal/entity/Proposal.java
  src/main/java/beyond/samdasoo/proposal/repository/ProposalRepositoryCustom.java
  src/main/java/beyond/samdasoo/proposal/repository/ProposalRepositoryImpl.java
  src/main/java/beyond/samdasoo/proposal/service/ProposalService.java
  src/main/resources/data.sql
Labels: backend, refact

#235 [Feat/#219] 더미데이터 추가
  src/main/resources/data.sql
Labels: backend, feat

#237 [feat/#236] 목표 매출 데이터 추가
  src/main/resources/data.sql
Labels: backend, feat

#238 [feat/236] 목표 매출 수정 api 수정
  src/main/java/beyond/samdasoo/admin/service/TargetSaleServiceImpl.java
Labels: backend, feat, refact

#240 [Feat/#239] 목표 매출 api 주석 제거
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
  src/main/resources/data.sql
Labels: backend, feat

#242 [Feat/#241] 삭제 api 수정 및 부서장 데이터 추가
  src/main/java/beyond/samdasoo/admin/service/DepartmentServiceImpl.java
  src/main/resources/data.sql
Labels: backend, feat

#244 [Fix/#243] testSales 엔티티 수정
  src/main/java/beyond/samdasoo/contract/entity/Contract.java
  src/main/java/beyond/samdasoo/estimate/entity/Estimate.java
  src/main/java/beyond/samdasoo/proposal/entity/Proposal.java
  src/main/java/beyond/samdasoo/testsales/dto/TestSalesResponseDto.java
  src/main/java/beyond/samdasoo/testsales/entity/TestSales.java
  src/main/resources/data.sql
Labels: bug, backend, 🚨hotfix
