Repository beyond-sw-camp/be08-fin-3Dasoo-SalesBoost-BE, pull requests merged in 2024-10, with the labels that each got.

#46 [Feat/#16] API tag & operation 추가 및 BaseResponse<List<>> 수정
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/estimate/controller/EstimateController.java
  src/main/java/beyond/samdasoo/estimate/dto/EstimateRequestDto.java
  src/main/java/beyond/samdasoo/estimate/dto/EstimateResponseDto.java
  src/main/java/beyond/samdasoo/estimate/entity/Estimate.java
  src/main/java/beyond/samdasoo/estimate/service/EstimateService.java
Labels: backend, refact

#50 [Refact/#49] proposal 응답 형식 변경
  src/main/java/beyond/samdasoo/proposal/service/ProposalService.java
Labels: backend, refact

#48 [Refact/#40] Act, Todo, Plan 기본 응답 형식 변경
  src/main/java/beyond/samdasoo/act/controller/ActController.java
  src/main/java/beyond/samdasoo/act/dto/ActRequestDto.java
  src/main/java/beyond/samdasoo/act/dto/ActResponseDto.java
  src/main/java/beyond/samdasoo/act/entity/Act.java
  src/main/java/beyond/samdasoo/act/service/ActService.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/plan/controller/PlanController.java
  src/main/java/beyond/samdasoo/plan/dto/PlanRequestDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanResponseDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanUpdateDto.java
  src/main/java/beyond/samdasoo/plan/entity/Plan.java
  src/main/java/beyond/samdasoo/plan/service/PlanService.java
  src/main/java/beyond/samdasoo/todo/controller/TodoController.java
  src/main/java/beyond/samdasoo/todo/dto/TodoResponseDto.java
  src/main/java/beyond/samdasoo/todo/entity/Todo.java
  src/main/java/beyond/samdasoo/todo/service/TodoService.java
Labels: backend, refact, docs

#52 [Feat/#47] 일정 관련 할 일 조회 API 추가
  src/main/java/beyond/samdasoo/act/controller/ActController.java
  src/main/java/beyond/samdasoo/plan/controller/PlanController.java
  src/main/java/beyond/samdasoo/plan/dto/PlanResponseDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanTodoResponseDto.java
  src/main/java/beyond/samdasoo/plan/entity/Plan.java
  src/main/java/beyond/samdasoo/plan/service/PlanService.java
  src/main/java/beyond/samdasoo/todo/controller/TodoController.java
  src/main/java/beyond/samdasoo/todo/dto/TodoRequestDto.java
  src/main/java/beyond/samdasoo/todo/dto/TodoResponseDto.java
  src/main/java/beyond/samdasoo/todo/entity/Todo.java
  src/main/java/beyond/samdasoo/todo/service/TodoService.java
Labels: backend, feat, style

#51 [Feat/#41] 도메인 별 응답 형식 적용, 변수타입, 변수명 변경
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/contract/controller/ContractController.java
  src/main/java/beyond/samdasoo/contract/entity/Contract.java
  src/main/java/beyond/samdasoo/contract/service/ContractService.java
  src/main/java/beyond/samdasoo/estimate/service/EstimateService.java
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/entity/Sales.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
Labels: backend, refact

#56 [Feat/#36] 잠재고객 관련 API 개발
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/lead/Lead.java
  src/main/java/beyond/samdasoo/potentialcustomer/controller/PotentialCustomerController.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/ContactHistoryDto.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/CreateContactHistoryReq.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/CreatePotentialCustomerReq.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/PotentialCustomerDto.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/PotentialCustomerListDto.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/UpdatePotentialCustomerReq.java
  src/main/java/beyond/samdasoo/potentialcustomer/entity/ContactHistory.java
  src/main/java/beyond/samdasoo/potentialcustomer/entity/PotentialCustomer.java
  src/main/java/beyond/samdasoo/potentialcustomer/repository/ContactHistoryRepository.java
  src/main/java/beyond/samdasoo/potentialcustomer/repository/PotentialCustomerRepository.java
  src/main/java/beyond/samdasoo/potentialcustomer/service/PotentialCustomerService.java
  src/main/java/beyond/samdasoo/user/entity/User.java
Labels: backend, feat

#58 [Feat/#55] 목표 매출 Entity 생성 및 API 구현
  src/main/java/beyond/samdasoo/admin/controller/TargetSaleController.java
  src/main/java/beyond/samdasoo/admin/dto/TargetSaleRequestDto.java
  src/main/java/beyond/samdasoo/admin/dto/TargetSaleResponseDto.java
  src/main/java/beyond/samdasoo/admin/entity/Product.java
  src/main/java/beyond/samdasoo/admin/entity/TargetSale.java
  src/main/java/beyond/samdasoo/admin/repository/ProductRepository.java
  src/main/java/beyond/samdasoo/admin/repository/TargetSaleRepository.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleService.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleServiceImpl.java
  src/main/java/beyond/samdasoo/user/entity/User.java
Labels: backend, feat

#60 [Feat/#57] 영업활동, 일정, 할 일 리스트 조회 API 추가
  src/main/java/beyond/samdasoo/act/controller/ActController.java
  src/main/java/beyond/samdasoo/act/service/ActService.java
  src/main/java/beyond/samdasoo/plan/controller/PlanController.java
  src/main/java/beyond/samdasoo/todo/controller/TodoController.java
  src/main/java/beyond/samdasoo/todo/service/TodoService.java
Labels: backend, feat

#61 [Feat/#59] 캘린더 엔티티 추가 및 캘린더 기능 전체 구조 변경
  src/main/java/beyond/samdasoo/act/dto/ActRequestDto.java
  src/main/java/beyond/samdasoo/act/dto/ActResponseDto.java
  src/main/java/beyond/samdasoo/act/entity/Act.java
  src/main/java/beyond/samdasoo/act/service/ActService.java
  src/main/java/beyond/samdasoo/calendar/controller/CalendarController.java
  src/main/java/beyond/samdasoo/calendar/dto/CalendarRequestDto.java
  src/main/java/beyond/samdasoo/calendar/dto/CalendarResponseDto.java
  src/main/java/beyond/samdasoo/calendar/entity/Calendar.java
  src/main/java/beyond/samdasoo/calendar/entity/CalendarType.java
  src/main/java/beyond/samdasoo/calendar/repository/CalendarRepository.java
  src/main/java/beyond/samdasoo/calendar/service/CalendarService.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/plan/controller/PlanController.java
  src/main/java/beyond/samdasoo/plan/dto/PlanRequestDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanResponseDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanUpdateDto.java
  src/main/java/beyond/samdasoo/plan/entity/Plan.java
  src/main/java/beyond/samdasoo/plan/service/PlanService.java
  src/main/java/beyond/samdasoo/todo/dto/TodoRequestDto.java
  src/main/java/beyond/samdasoo/todo/dto/TodoResponseDto.java
  src/main/java/beyond/samdasoo/todo/dto/TodoUpdateDto.java
  src/main/java/beyond/samdasoo/todo/entity/Todo.java
  src/main/java/beyond/samdasoo/todo/service/TodoService.java
Labels: backend, feat, refact

#65 [Feat/#6] 유저 Entity 변경 및 API 수정
  .gitignore
  build.gradle
  src/main/java/beyond/samdasoo/common/entity/BaseEntity.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/dto/JoinUserReq.java
  src/main/java/beyond/samdasoo/user/dto/UpdateUserReq.java
  src/main/java/beyond/samdasoo/user/entity/User.java
  src/main/java/beyond/samdasoo/user/repository/UserRepository.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
  src/test/java/beyond/samdasoo/user/repository/UserRepositoryTest.java
Labels: backend, refact, test

#67 [Refact/#6] User 관련 API 리팩토링
  .idea/modules.xml
  .idea/modules/samdasoo.test.iml
  src/main/java/beyond/samdasoo/admin/entity/Department.java
  src/main/java/beyond/samdasoo/admin/repository/DepartmentRepository.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/dto/JoinUserReq.java
  src/main/java/beyond/samdasoo/user/dto/JoinUserRes.java
  src/main/java/beyond/samdasoo/user/dto/LoginUserReq.java
  src/main/java/beyond/samdasoo/user/entity/User.java
  src/main/java/beyond/samdasoo/user/repository/UserRepository.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
  src/main/resources/data.sql
  src/test/java/beyond/samdasoo/user/repository/UserRepositoryTest.java
Labels: backend, refact

#70 [Feat/#37] 고객 조회 & 등록 API 구현
  .idea/modules.xml
  .idea/modules/samdasoo.main.iml
  .idea/sqldialects.xml
  src/main/java/beyond/samdasoo/common/initDB/InitDB.java
  src/main/java/beyond/samdasoo/customer/Customer.java
  src/main/java/beyond/samdasoo/customer/controller/CustomerController.java
  src/main/java/beyond/samdasoo/customer/dto/CustomerCreateReq.java
  src/main/java/beyond/samdasoo/customer/dto/CustomerCreateRes.java
  src/main/java/beyond/samdasoo/customer/dto/CustomerGetRes.java
  src/main/java/beyond/samdasoo/customer/entity/Customer.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepository.java
  src/main/java/beyond/samdasoo/customer/service/CustomerService.java
  src/main/resources/data.sql
Labels: backend, feat

#72 [Feat/#37] 고객 정보 상세 조회 API 구현
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/customer/controller/CustomerController.java
  src/main/java/beyond/samdasoo/customer/dto/CustomerGetRes.java
  src/main/java/beyond/samdasoo/customer/dto/CustomersGetRes.java
  src/main/java/beyond/samdasoo/customer/service/CustomerService.java
  src/main/resources/data.sql
Labels: backend, feat

#75 [Feat/#71] 캘린더 보유 여부 검증 로직
  src/main/java/beyond/samdasoo/calendar/controller/CalendarController.java
  src/main/java/beyond/samdasoo/calendar/dto/CalendarRequestDto.java
  src/main/java/beyond/samdasoo/calendar/dto/CalendarResponseDto.java
  src/main/java/beyond/samdasoo/calendar/entity/Calendar.java
  src/main/java/beyond/samdasoo/calendar/entity/CalendarType.java
  src/main/java/beyond/samdasoo/calendar/repository/CalendarRepository.java
  src/main/java/beyond/samdasoo/calendar/service/CalendarService.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/plan/entity/PlanStatus.java
Labels: backend, feat

#73 [Feat/#69] 영업기회 API 구현
  .idea/compiler.xml
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/estimate/entity/EstProduct.java
  src/main/java/beyond/samdasoo/estimate/entity/Estimate.java
  src/main/java/beyond/samdasoo/lead/Entity/AwarePath.java
  src/main/java/beyond/samdasoo/lead/Entity/Lead.java
  src/main/java/beyond/samdasoo/lead/Entity/LeadStatus.java
  src/main/java/beyond/samdasoo/lead/Lead.java
  src/main/java/beyond/samdasoo/lead/controller/LeadController.java
  src/main/java/beyond/samdasoo/lead/dto/LeadRequestDto.java
  src/main/java/beyond/samdasoo/lead/dto/LeadResponseDto.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepository.java
  src/main/java/beyond/samdasoo/lead/service/LeadService.java
  src/main/java/beyond/samdasoo/proposal/entity/Proposal.java
  src/main/java/beyond/samdasoo/proposal/service/ProposalService.java
Labels: backend, feat, refact

#81 [Feat/#80] 부서 Dto 수정
  src/main/java/beyond/samdasoo/admin/dto/DepartmentDto.java
  src/main/java/beyond/samdasoo/admin/dto/ProductResponseDto.java
  src/main/java/beyond/samdasoo/admin/service/DepartmentServiceImpl.java
Labels: backend, feat

#84 [Feat/#74] Redis 설정 추가
  src/main/java/beyond/samdasoo/common/config/RedisConfig.java
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
  src/main/java/beyond/samdasoo/common/jwt/RefreshTokenRepository.java
  src/main/java/beyond/samdasoo/common/jwt/entity/RefreshToken.java
  src/main/java/beyond/samdasoo/common/jwt/service/RefreshTokenService.java
  src/main/java/beyond/samdasoo/common/utils/CookieUtil.java
  src/main/java/beyond/samdasoo/common/utils/JwtUtil.java
  src/main/java/beyond/samdasoo/test/TestController.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
Labels: backend, feat, refact

#86 [Feat/#85] 메인 인증코드 전송
  build.gradle
  src/main/java/beyond/samdasoo/common/email/CertificationNumber.java
  src/main/java/beyond/samdasoo/common/email/EmailProvider.java
  src/main/java/beyond/samdasoo/user/dto/SendEmailCodeReq.java
Labels: backend, feat

#87 [Feat/#85] 메일 인증 코드 검증
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
  src/main/java/beyond/samdasoo/common/email/EmailRepository.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/dto/EmailCodeCheckReq.java
  src/main/java/beyond/samdasoo/user/dto/SendEmailCodeReq.java
  src/main/java/beyond/samdasoo/user/repository/UserRepository.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
Labels: backend, feat

#89 [Feat/#82] 영업기회 필터 검색 api 추가
  .idea/compiler.xml
  .idea/modules/samdasoo.main.iml
  build.gradle
  src/main/java/beyond/samdasoo/admin/repository/SubProcessRepository.java
  src/main/java/beyond/samdasoo/common/config/QuerydslConfig.java
  src/main/java/beyond/samdasoo/common/config/SwaggerConfig.java
  src/main/java/beyond/samdasoo/excel/controller/ExcelController.java
  src/main/java/beyond/samdasoo/excel/service/ExcelService.java
  src/main/java/beyond/samdasoo/lead/Entity/Lead.java
  src/main/java/beyond/samdasoo/lead/Entity/Step.java
  src/main/java/beyond/samdasoo/lead/controller/LeadController.java
  src/main/java/beyond/samdasoo/lead/dto/LeadRequestDto.java
  src/main/java/beyond/samdasoo/lead/dto/LeadResponseDto.java
  src/main/java/beyond/samdasoo/lead/dto/LeadSearchCond.java
  src/main/java/beyond/samdasoo/lead/dto/StepResponseDto.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepository.java
  src/main/java/beyond/samdasoo/lead/repository/StepRepository.java
  src/main/java/beyond/samdasoo/lead/service/LeadService.java
Labels: backend, feat, refact, docs

#98 [Refact/#97] Lead 생성 및 수정 서비스 코드 수정
  src/main/java/beyond/samdasoo/admin/dto/ProcessResponseDto.java
  src/main/java/beyond/samdasoo/admin/dto/SubProcessResponseDto.java
  src/main/java/beyond/samdasoo/lead/controller/LeadController.java
  src/main/java/beyond/samdasoo/lead/dto/LeadResponseDto.java
  src/main/java/beyond/samdasoo/lead/repository/StepRepository.java
  src/main/java/beyond/samdasoo/lead/service/LeadService.java
Labels: backend, refact

#100 [Refact/#94] 잠재고객 관련 API 수정
  src/main/java/beyond/samdasoo/common/jwt/entity/RefreshToken.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/common/utils/CookieUtil.java
  src/main/java/beyond/samdasoo/common/utils/JwtUtil.java
  src/main/java/beyond/samdasoo/potentialcustomer/controller/PotentialCustomerController.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/CreatePotentialCustomerReq.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/PotentialCustomerDto.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/PotentialCustomerListDto.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/UpdatePotentialCustomerReq.java
  src/main/java/beyond/samdasoo/potentialcustomer/entity/PotentialCustomer.java
  src/main/java/beyond/samdasoo/potentialcustomer/service/PotentialCustomerService.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
  src/main/resources/data.sql
Labels: backend, refact

#101 [Feat/#99] 영업 활동차트 관련 API 추가
  src/main/java/beyond/samdasoo/act/controller/ActController.java
  src/main/java/beyond/samdasoo/act/dto/ActResponseDto.java
  src/main/java/beyond/samdasoo/act/entity/Act.java
  src/main/java/beyond/samdasoo/act/entity/ActStatus.java
  src/main/java/beyond/samdasoo/act/service/ActService.java
  src/main/resources/base.sql
Labels: backend, feat

#108 [Fix] Plan 수정 시 객체 반환
  src/main/java/beyond/samdasoo/plan/controller/PlanController.java
  src/main/java/beyond/samdasoo/plan/service/PlanService.java
  src/main/resources/base.sql
Labels: bug, backend, chore

#114 [Feat/#112] 목표 매출(/프로세스) 관련 api 수정
  src/main/generated/beyond/samdasoo/act/entity/QAct.java
  src/main/generated/beyond/samdasoo/admin/entity/QDepartment.java
  src/main/generated/beyond/samdasoo/admin/entity/QProcess.java
  src/main/generated/beyond/samdasoo/admin/entity/QProduct.java
  src/main/generated/beyond/samdasoo/admin/entity/QSubProcess.java
  src/main/generated/beyond/samdasoo/admin/entity/QTargetSale.java
  src/main/generated/beyond/samdasoo/calendar/entity/QCalendar.java
  src/main/generated/beyond/samdasoo/common/entity/QBaseEntity.java
  src/main/generated/beyond/samdasoo/contract/entity/QContract.java
  src/main/generated/beyond/samdasoo/customer/entity/QCustomer.java
  src/main/generated/beyond/samdasoo/estimate/entity/QEstProduct.java
  src/main/generated/beyond/samdasoo/estimate/entity/QEstimate.java
  src/main/generated/beyond/samdasoo/lead/Entity/QLead.java
  src/main/generated/beyond/samdasoo/lead/Entity/QStep.java
  src/main/generated/beyond/samdasoo/plan/entity/QPlan.java
  src/main/generated/beyond/samdasoo/potentialcustomer/entity/QContactHistory.java
  src/main/generated/beyond/samdasoo/potentialcustomer/entity/QPotentialCustomer.java
  src/main/generated/beyond/samdasoo/proposal/entity/QProposal.java
  src/main/generated/beyond/samdasoo/sales/entity/QSales.java
  src/main/generated/beyond/samdasoo/todo/entity/QTodo.java
  src/main/generated/beyond/samdasoo/user/entity/QUser.java
  src/main/java/beyond/samdasoo/admin/controller/TargetSaleController.java
  src/main/java/beyond/samdasoo/admin/dto/SubProcessRequestDto.java
  src/main/java/beyond/samdasoo/admin/dto/SubProcessResponseDto.java
  src/main/java/beyond/samdasoo/admin/dto/TargetSaleResponseDto.java
  src/main/java/beyond/samdasoo/admin/entity/SubProcess.java
  src/main/java/beyond/samdasoo/admin/service/SubProcessServiceImpl.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleService.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleServiceImpl.java
  src/main/java/beyond/samdasoo/user/repository/UserRepository.java
Labels: backend

#116 [Product/#79] responseDto 수정 및 api 수정
  src/main/java/beyond/samdasoo/admin/dto/ProductResponseDto.java
  src/main/java/beyond/samdasoo/admin/service/ProductService.java
Labels: backend

#118 [Feat/#117] 부서 api 및 dto 수정
  src/main/java/beyond/samdasoo/admin/dto/DepartmentDto.java
  src/main/java/beyond/samdasoo/admin/dto/DepartmentRequestDto.java
  src/main/java/beyond/samdasoo/admin/service/DepartmentServiceImpl.java
Labels: backend, feat

#119 [Feat/#106] 메인페이지 고객, 잠재고객, 영업기회, 영업활동 통계 api 추가
  src/main/java/beyond/samdasoo/act/controller/ActController.java
  src/main/java/beyond/samdasoo/act/dto/ActStatusDto.java
  src/main/java/beyond/samdasoo/act/repository/ActRepository.java
  src/main/java/beyond/samdasoo/act/repository/ActRepositoryCustom.java
  src/main/java/beyond/samdasoo/act/repository/ActRepositoryImpl.java
  src/main/java/beyond/samdasoo/act/service/ActService.java
  src/main/java/beyond/samdasoo/customer/controller/CustomerController.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepositoryCustom.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepositoryImpl.java
  src/main/java/beyond/samdasoo/customer/service/CustomerService.java
  src/main/java/beyond/samdasoo/lead/controller/LeadController.java
  src/main/java/beyond/samdasoo/lead/dto/LeadStatusDto.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepositoryCustom.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepositoryImpl.java
  src/main/java/beyond/samdasoo/lead/service/LeadService.java
  src/main/java/beyond/samdasoo/potentialcustomer/controller/PotentialCustomerController.java
  src/main/java/beyond/samdasoo/potentialcustomer/repository/PotentialCustomerRepositoryCustom.java
  src/main/java/beyond/samdasoo/potentialcustomer/repository/PotentialCustomerRepositoryImpl.java
  src/main/java/beyond/samdasoo/potentialcustomer/service/PotentialCustomerService.java
  src/main/java/beyond/samdasoo/user/repository/UserRepositoryImpl.java
Labels: backend, feat

#120 [Feat/#111] 사용자 인증 기반 캘린더 관리 구현
  src/main/java/beyond/samdasoo/act/entity/Act.java
  src/main/java/beyond/samdasoo/calendar/controller/CalendarController.java
  src/main/java/beyond/samdasoo/calendar/dto/CalendarResponseDto.java
  src/main/java/beyond/samdasoo/calendar/entity/Calendar.java
  src/main/java/beyond/samdasoo/calendar/repository/CalendarRepository.java
  src/main/java/beyond/samdasoo/calendar/service/CalendarService.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
  src/main/resources/base.sql
Labels: bug, backend, feat, refact

#121 [Feat/#106] 메인페이지 연/월간 매출, 목표매출 통계 api 추가
  src/main/java/beyond/samdasoo/admin/controller/TargetSaleController.java
  src/main/java/beyond/samdasoo/admin/dto/TargetSalesStatusDto.java
  src/main/java/beyond/samdasoo/admin/repository/TargetSaleRepository.java
  src/main/java/beyond/samdasoo/admin/repository/TargetSaleRepositoryCustom.java
  src/main/java/beyond/samdasoo/admin/repository/TargetSaleRepositoryImpl.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleService.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleServiceImpl.java
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/dto/SalesStatusDto.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepository.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepositoryCustom.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepositoryImpl.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
Labels: backend, feat

#125 [Feat/#112] 목표 매출 api 및 dto 수정
  src/main/java/beyond/samdasoo/admin/dto/TargetSaleRequestDto.java
  src/main/java/beyond/samdasoo/admin/repository/ProductRepository.java
  src/main/java/beyond/samdasoo/admin/service/TargetSaleServiceImpl.java
Labels: backend, feat

#128 [Test/#123] 캘린더 Service 테스트
  src/main/java/beyond/samdasoo/calendar/entity/Calendar.java
  src/main/java/beyond/samdasoo/calendar/service/CalendarService.java
  src/test/java/beyond/samdasoo/calendar/service/CalendarServiceTest.java
Labels: backend, test

#129 [Feat/#127] 사용자 권한별 인증/인가
  src/main/java/beyond/samdasoo/admin/controller/AdminController.java
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
  src/main/java/beyond/samdasoo/common/filter/AuthenticationFilter.java
  src/main/java/beyond/samdasoo/common/jwt/JwtAuthenticationFilter.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/user/CustomUserDetails.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/dto/LoginUserReq.java
  src/main/java/beyond/samdasoo/user/dto/LoginUserRes.java
  src/main/java/beyond/samdasoo/user/service/CustomUserDetailService.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
  src/main/resources/data.sql
Labels: backend, feat, refact

#133 [feat/#132] TargetSales url 수정
  src/main/java/beyond/samdasoo/admin/controller/TargetSaleController.java
Labels: backend, refact

#136 [Feat/#78] 예측 기능 구현 및 더미데이터 수정
  .idea/dataSources.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/sqldialects.xml
  src/main/java/beyond/samdasoo/contract/entity/Contract.java
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/dto/SalesPredictionDto.java
  src/main/java/beyond/samdasoo/sales/dto/SalesResponseDto.java
  src/main/java/beyond/samdasoo/sales/entity/Sales.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepository.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
  src/main/resources/base.sql
Labels: backend, feat, refact

#135 [Feat/#117] 부서 관련 조회 api 수정 및 url 변경
  src/main/java/beyond/samdasoo/admin/controller/DepartmentController.java
  src/main/java/beyond/samdasoo/admin/service/DepartmentServiceImpl.java
Labels: backend, refact

#138 [Feat/#137] 프로세스 / 하위 프로세스 api 수정 및 url 변경
  src/main/java/beyond/samdasoo/admin/controller/ProcessController.java
  src/main/java/beyond/samdasoo/admin/controller/SubProcessController.java
  src/main/java/beyond/samdasoo/admin/service/ProcessServiceImpl.java
  src/main/java/beyond/samdasoo/admin/service/SubProcessService.java
  src/main/java/beyond/samdasoo/admin/service/SubProcessServiceImpl.java
Labels: backend, refact

#140 [Feat/#139] 견적 등록 및 수정 시 견적별 제품 연결
  src/main/java/beyond/samdasoo/estimate/controller/EstimateController.java
  src/main/java/beyond/samdasoo/estimate/dto/CreateEstProductDto.java
  src/main/java/beyond/samdasoo/estimate/dto/CreateEstimateDto.java
  src/main/java/beyond/samdasoo/estimate/dto/EstimateRequestDto.java
  src/main/java/beyond/samdasoo/estimate/entity/Estimate.java
  src/main/java/beyond/samdasoo/estimate/service/EstimateService.java
Labels: backend, feat

#141 [Test/#130] Todo 서비스 테스트 수행
  src/main/java/beyond/samdasoo/todo/dto/TodoRequestDto.java
  src/main/java/beyond/samdasoo/todo/dto/TodoUpdateDto.java
  src/test/java/beyond/samdasoo/todo/service/TodoServiceTest.java
Labels: backend, test

#142 [Test/#131] Plan 서비스 테스트 수행
  src/main/java/beyond/samdasoo/plan/dto/PlanRequestDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanTodoResponseDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanUpdateDto.java
  src/test/java/beyond/samdasoo/plan/service/PlanServiceTest.java
Labels: backend, test

#145 [Feat/#79] 제품 생성 api 오류 수정 및 url 변경
  src/main/java/beyond/samdasoo/admin/controller/DepartmentController.java
  src/main/java/beyond/samdasoo/admin/controller/ProductController.java
  src/main/java/beyond/samdasoo/admin/service/ProductServiceImpl.java
Labels: backend, refact

#146 [Fix/#144] 잠재고객 등록에러 해결
  .idea/misc.xml
  src/main/java/beyond/samdasoo/potentialcustomer/dto/CreatePotentialCustomerReq.java
  src/main/java/beyond/samdasoo/potentialcustomer/entity/PotentialCustomer.java
  src/main/java/beyond/samdasoo/potentialcustomer/service/PotentialCustomerService.java
Labels: bug, backend

#147 [Feat/#137] 프로세스 수정/생성 api 수정 및 dto 수정
  src/main/java/beyond/samdasoo/admin/dto/ProcessRequestDto.java
  src/main/java/beyond/samdasoo/admin/repository/ProcessRepository.java
  src/main/java/beyond/samdasoo/admin/service/ProcessServiceImpl.java
Labels: backend, feat, refact

#148 [Fix/#144] 캘린더 에러 수정
  src/main/java/beyond/samdasoo/calendar/controller/CalendarController.java
Labels: backend

#150 [Feat/#122] Customer 필터 검색 api 추가
  .idea/misc.xml
  .idea/sqldialects.xml
  src/main/java/beyond/samdasoo/admin/repository/TargetSaleRepositoryImpl.java
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
  src/main/java/beyond/samdasoo/customer/controller/CustomerController.java
  src/main/java/beyond/samdasoo/customer/dto/PopupCustomerGetRes.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepository.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepositoryCustom.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepositoryImpl.java
  src/main/java/beyond/samdasoo/customer/service/CustomerService.java
  src/main/java/beyond/samdasoo/lead/controller/LeadController.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepositoryImpl.java
  src/main/resources/base.sql
Labels: backend, feat, refact

#152 [Feat/#137] 하위 프로세스 생성 api 수정 및 sql 파일 수정
  src/main/java/beyond/samdasoo/admin/service/SubProcessServiceImpl.java
  src/main/resources/base.sql
  src/main/resources/data.sql
Labels: bug, backend, refact

#155 [Feat/#154] 고객 삭제, 수정 로직 변경
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/customer/controller/CustomerController.java
  src/main/java/beyond/samdasoo/customer/dto/CustomerGetRes.java
  src/main/java/beyond/samdasoo/customer/service/CustomerService.java
Labels: backend, feat, refact

#156 [Fix/#153] sample 쿼리문 수정
  src/main/resources/base.sql
Labels: bug, backend

#157 [Feat/#122] 영업기회 파이프라인 관련 api 추가
  src/main/java/beyond/samdasoo/act/controller/ActController.java
  src/main/java/beyond/samdasoo/act/repository/ActRepository.java
  src/main/java/beyond/samdasoo/act/service/ActService.java
  src/main/java/beyond/samdasoo/contract/controller/ContractController.java
  src/main/java/beyond/samdasoo/contract/dto/ContractResponseDto.java
  src/main/java/beyond/samdasoo/contract/repository/ContractRepository.java
  src/main/java/beyond/samdasoo/contract/repository/ContractRepositoryCustom.java
  src/main/java/beyond/samdasoo/contract/repository/ContractRepositoryImpl.java
  src/main/java/beyond/samdasoo/contract/service/ContractService.java
  src/main/java/beyond/samdasoo/estimate/controller/EstimateController.java
  src/main/java/beyond/samdasoo/estimate/dto/EstimateResponseDto.java
  src/main/java/beyond/samdasoo/estimate/entity/Estimate.java
  src/main/java/beyond/samdasoo/estimate/repository/EstimateRepository.java
  src/main/java/beyond/samdasoo/estimate/repository/EstimateRepositoryCustom.java
  src/main/java/beyond/samdasoo/estimate/repository/EstimateRepositoryImpl.java
  src/main/java/beyond/samdasoo/estimate/service/EstimateService.java
  src/main/java/beyond/samdasoo/lead/Entity/Lead.java
  src/main/java/beyond/samdasoo/lead/dto/LeadRequestDto.java
  src/main/java/beyond/samdasoo/lead/dto/LeadResponseDto.java
  src/main/java/beyond/samdasoo/proposal/controller/ProposalController.java
  src/main/java/beyond/samdasoo/proposal/dto/ProposalResponseDto.java
  src/main/java/beyond/samdasoo/proposal/repository/ProposalRepository.java
  src/main/java/beyond/samdasoo/proposal/repository/ProposalRepositoryCustom.java
  src/main/java/beyond/samdasoo/proposal/repository/ProposalRepositoryImpl.java
  src/main/java/beyond/samdasoo/proposal/service/ProposalService.java
  src/main/java/beyond/samdasoo/sales/dto/SalesResponseDto.java
Labels: bug, backend, feat

#158 refact : #78 sales 부분 체크, 전체 기능 체크
  src/main/java/beyond/samdasoo/sales/dto/SalesRequestDto.java
  src/main/java/beyond/samdasoo/sales/dto/SalesResponseDto.java
  src/main/java/beyond/samdasoo/sales/entity/Sales.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
  src/main/resources/base.sql
Labels: backend, refact

#160 [Feat/#159] 고객 삭제, 수정 로직 변경
  src/main/java/beyond/samdasoo/potentialcustomer/controller/PotentialCustomerController.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/CreatePotentialCustomerReq.java
  src/main/java/beyond/samdasoo/potentialcustomer/dto/PotentialCustomerDto.java
  src/main/java/beyond/samdasoo/potentialcustomer/entity/PotentialCustomer.java
  src/main/java/beyond/samdasoo/potentialcustomer/service/PotentialCustomerService.java
  src/main/java/beyond/samdasoo/user/entity/User.java
  src/main/resources/data.sql
Labels: backend, feat

#162 [Feat/#161] CI/CD 파이프라인 구현, Docker Hub로 자동 push
  .github/workflows/ci-cd.yml
  Dockerfile
  docker-compose.yml
Labels: backend, deploy

#163 [Feat/#137] 기본 프로세스 관련 수정 생성 api 수정
  src/main/java/beyond/samdasoo/admin/service/ProcessServiceImpl.java
Labels: backend, refact

#164 [Feat/#122] 메인화면 부서 검색조건 추가
  src/main/java/beyond/samdasoo/act/repository/ActRepositoryCustom.java
  src/main/java/beyond/samdasoo/act/repository/ActRepositoryImpl.java
  src/main/java/beyond/samdasoo/act/service/ActService.java
  src/main/java/beyond/samdasoo/admin/repository/SubProcessRepository.java
  src/main/java/beyond/samdasoo/admin/repository/SubProcessRepositoryCustom.java
  src/main/java/beyond/samdasoo/admin/repository/SubProcessRepositoryImpl.java
  src/main/java/beyond/samdasoo/admin/repository/TargetSaleRepositoryImpl.java
  src/main/java/beyond/samdasoo/common/dto/SearchCond.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/contract/controller/ContractController.java
  src/main/java/beyond/samdasoo/contract/repository/ContractRepositoryCustom.java
  src/main/java/beyond/samdasoo/contract/repository/ContractRepositoryImpl.java
  src/main/java/beyond/samdasoo/contract/service/ContractService.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepositoryCustom.java
  src/main/java/beyond/samdasoo/customer/repository/CustomerRepositoryImpl.java
  src/main/java/beyond/samdasoo/customer/service/CustomerService.java
  src/main/java/beyond/samdasoo/estimate/controller/EstimateController.java
  src/main/java/beyond/samdasoo/estimate/entity/Estimate.java
  src/main/java/beyond/samdasoo/estimate/repository/EstimateRepositoryCustom.java
  src/main/java/beyond/samdasoo/estimate/repository/EstimateRepositoryImpl.java
  src/main/java/beyond/samdasoo/estimate/service/EstimateService.java
  src/main/java/beyond/samdasoo/lead/Entity/Lead.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepositoryCustom.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepositoryImpl.java
  src/main/java/beyond/samdasoo/lead/service/LeadService.java
  src/main/java/beyond/samdasoo/potentialcustomer/repository/PotentialCustomerRepositoryCustom.java
  src/main/java/beyond/samdasoo/potentialcustomer/repository/PotentialCustomerRepositoryImpl.java
  src/main/java/beyond/samdasoo/potentialcustomer/service/PotentialCustomerService.java
  src/main/java/beyond/samdasoo/proposal/service/ProposalService.java
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepositoryCustom.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepositoryImpl.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
  src/main/java/beyond/samdasoo/user/repository/UserRepositoryCustom.java
  src/main/java/beyond/samdasoo/user/repository/UserRepositoryImpl.java
  src/main/resources/base.sql
Labels: backend, feat, refact

#166 [Feat/#117] 부서 관련 엔티티 수정 및 외래키 조건 수정
  src/main/java/beyond/samdasoo/admin/dto/ProductResponseDto.java
  src/main/java/beyond/samdasoo/admin/entity/Department.java
  src/main/java/beyond/samdasoo/admin/entity/Product.java
  src/main/java/beyond/samdasoo/admin/repository/DepartmentRepository.java
  src/main/java/beyond/samdasoo/admin/service/DepartmentServiceImpl.java
  src/main/java/beyond/samdasoo/admin/service/ProductServiceImpl.java
  src/main/java/beyond/samdasoo/user/entity/User.java
  src/main/resources/base.sql
Labels: bug, backend, refact

#167 [Feat/#165] 비밀번호 변경 API 구현
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
  src/main/java/beyond/samdasoo/common/email/EmailProvider.java
  src/main/java/beyond/samdasoo/common/jwt/JwtAuthenticationFilter.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/potentialcustomer/entity/PotentialCustomer.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/dto/UpdatePasswordReq.java
  src/main/java/beyond/samdasoo/user/dto/UpdatePasswordRequestReq.java
  src/main/java/beyond/samdasoo/user/dto/UpdatePasswordToken.java
  src/main/java/beyond/samdasoo/user/entity/User.java
  src/main/java/beyond/samdasoo/user/repository/UpdatePasswordTokenRedisRepository.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
  src/main/resources/base.sql
  src/main/resources/data.sql
Labels: backend, feat

#168 [Feat/#137] 하위 프로세스 수정 삭제시 프로세스 예상 소요 기간도 변경되도록 수정
  src/main/java/beyond/samdasoo/admin/service/SubProcessServiceImpl.java
Labels: backend, refact
