Repository beyond-sw-camp/be08-fin-3Dasoo-SalesBoost-BE, pull requests merged in 2024-09, with the labels that each got.

#11 [Feat/#4] 할 일 Entity, 등록 및 단건 조회 API
  src/main/java/beyond/samdasoo/todo/controller/TodoController.java
  src/main/java/beyond/samdasoo/todo/dto/TodoRequestDto.java
  src/main/java/beyond/samdasoo/todo/dto/TodoResponseDto.java
  src/main/java/beyond/samdasoo/todo/entity/Todo.java
  src/main/java/beyond/samdasoo/todo/entity/TodoStatus.java
  src/main/java/beyond/samdasoo/todo/repository/TodoRepository.java
  src/main/java/beyond/samdasoo/todo/service/TodoService.java
Labels: backend, feat

#15 [Feat/#10] 제안 Entity, 등록 및 특정 제안 조회 API
  src/main/java/beyond/samdasoo/proposal/controller/ProposalController.java
  src/main/java/beyond/samdasoo/proposal/dto/ProposalRequestDto.java
  src/main/java/beyond/samdasoo/proposal/dto/ProposalResponseDto.java
  src/main/java/beyond/samdasoo/proposal/entity/Proposal.java
  src/main/java/beyond/samdasoo/proposal/repository/ProposalRepository.java
  src/main/java/beyond/samdasoo/proposal/service/ProposalService.java
Labels: backend, feat

#13 [Chore/#12] SecurityConfig CORS/CSRF 설정 및 Swagger 추가
  build.gradle
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
  src/main/java/beyond/samdasoo/common/config/SwaggerConfig.java
Labels: backend, chore

#23 [Feat/#9] 일정 등록, 조회, 수정, 삭제 API
  src/main/java/beyond/samdasoo/plan/controller/PlanController.java
  src/main/java/beyond/samdasoo/plan/dto/PlanRequestDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanResponseDto.java
  src/main/java/beyond/samdasoo/plan/dto/PlanUpdateDto.java
  src/main/java/beyond/samdasoo/plan/entity/Plan.java
  src/main/java/beyond/samdasoo/plan/entity/PlanStatus.java
  src/main/java/beyond/samdasoo/plan/repository/PlanRepository.java
  src/main/java/beyond/samdasoo/plan/service/PlanService.java
Labels: backend, feat

#25 [Feat/#22] 응답 형식 추가, 유저 API 수정
  src/main/java/beyond/samdasoo/common/exception/BaseException.java
  src/main/java/beyond/samdasoo/common/exception/GlobalExceptionHandler.java
  src/main/java/beyond/samdasoo/common/response/BaseResponse.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/member/entity/Member.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/dto/UserDto.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
Labels: backend, feat, refact

#28 [Refact/#4] User 반영 및 Swagger 개선
  src/main/java/beyond/samdasoo/member/controller/MemberController.java
  src/main/java/beyond/samdasoo/member/entity/Alarm.java
  src/main/java/beyond/samdasoo/member/entity/Member.java
  src/main/java/beyond/samdasoo/member/repository/MemberRepository.java
  src/main/java/beyond/samdasoo/member/service/MemberService.java
  src/main/java/beyond/samdasoo/plan/service/PlanService.java
  src/main/java/beyond/samdasoo/todo/controller/TodoController.java
  src/main/java/beyond/samdasoo/todo/dto/TodoRequestDto.java
  src/main/java/beyond/samdasoo/todo/dto/TodoResponseDto.java
  src/main/java/beyond/samdasoo/todo/dto/TodoUpdateDto.java
  src/main/java/beyond/samdasoo/todo/entity/Todo.java
  src/main/java/beyond/samdasoo/todo/entity/TodoStatus.java
  src/main/java/beyond/samdasoo/todo/service/TodoService.java
Labels: backend, refact, docs, style

#33 [Feat/#27] Access Token 발급
  src/main/java/beyond/samdasoo/common/config/SecurityConfig.java
  src/main/java/beyond/samdasoo/common/entity/BaseEntity.java
  src/main/java/beyond/samdasoo/common/exception/GlobalExceptionHandler.java
  src/main/java/beyond/samdasoo/common/exception/JwtAuthenticationEntrypoint.java
  src/main/java/beyond/samdasoo/common/jwt/JwtAuthenticationFilter.java
  src/main/java/beyond/samdasoo/common/jwt/JwtTokenProvider.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
  src/main/java/beyond/samdasoo/lead/Lead.java
  src/main/java/beyond/samdasoo/lead/repository/LeadRepository.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/dto/LoginUserRes.java
  src/main/java/beyond/samdasoo/user/dto/UserDto.java
  src/main/java/beyond/samdasoo/user/entity/User.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
Labels: backend, feat

#35 [Feat/#27] Authentication에 저장된 사용자 이메일 조회 함수 구현
  src/main/java/beyond/samdasoo/common/utils/UserUtil.java
  src/main/java/beyond/samdasoo/user/controller/UserController.java
  src/main/java/beyond/samdasoo/user/service/UserService.java
Labels: backend, feat

#34 [Feat/#7] 계약 등록, 조회, 수정, 삭제 API 추가
  src/main/java/beyond/samdasoo/contract/controller/ContractController.java
  src/main/java/beyond/samdasoo/contract/dto/ContractRequestDto.java
  src/main/java/beyond/samdasoo/contract/dto/ContractResponseDto.java
  src/main/java/beyond/samdasoo/contract/entity/Contract.java
  src/main/java/beyond/samdasoo/contract/repository/ContractRepository.java
  src/main/java/beyond/samdasoo/contract/service/ContractService.java
Labels: backend, feat

#29 [Feat/#14] 제품 Entity, 기본기능 (제품 등록, 모두 조회, 이름으로 조회) API
  src/main/java/beyond/samdasoo/admin/controller/ProductController.java
  src/main/java/beyond/samdasoo/admin/dto/ProductRequestDto.java
  src/main/java/beyond/samdasoo/admin/dto/ProductResponseDto.java
  src/main/java/beyond/samdasoo/admin/entity/Product.java
  src/main/java/beyond/samdasoo/admin/repository/ProductRepository.java
  src/main/java/beyond/samdasoo/admin/service/ProductService.java
  src/main/java/beyond/samdasoo/admin/service/ProductServiceImpl.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
Labels: backend, feat

#38 [Sales/#32] sales 부분 조회, 수정, 생성, 삭제 기능 구현
  README.md
  build.gradle
  src/main/java/beyond/samdasoo/sales/controller/SalesController.java
  src/main/java/beyond/samdasoo/sales/dto/SalesRequestDto.java
  src/main/java/beyond/samdasoo/sales/dto/SalesResponseDto.java
  src/main/java/beyond/samdasoo/sales/entity/Sales.java
  src/main/java/beyond/samdasoo/sales/repository/SalesRepository.java
  src/main/java/beyond/samdasoo/sales/service/SalesService.java
Labels: backend, feat

#30 [Feat/#5] 엑셀 다운로드 기능 추가
  build.gradle
  src/main/java/beyond/samdasoo/excel/controller/ExcelController.java
  src/main/java/beyond/samdasoo/excel/dto/ExcelDto.java
  src/main/java/beyond/samdasoo/excel/service/ExcelService.java
Labels: backend, feat

#42 [Process/#31] 프로세스/하위 프로세스 엔티티 작성 및 api 작성
  src/main/java/beyond/samdasoo/admin/controller/ProcessController.java
  src/main/java/beyond/samdasoo/admin/controller/ProductController.java
  src/main/java/beyond/samdasoo/admin/controller/SubProcessController.java
  src/main/java/beyond/samdasoo/admin/dto/ProcessRequestDto.java
  src/main/java/beyond/samdasoo/admin/dto/ProcessResponseDto.java
  src/main/java/beyond/samdasoo/admin/dto/SubProcessRequestDto.java
  src/main/java/beyond/samdasoo/admin/dto/SubProcessResponseDto.java
  src/main/java/beyond/samdasoo/admin/entity/Process.java
  src/main/java/beyond/samdasoo/admin/entity/SubProcess.java
  src/main/java/beyond/samdasoo/admin/repository/ProcessRepository.java
  src/main/java/beyond/samdasoo/admin/repository/SubProcessRepository.java
  src/main/java/beyond/samdasoo/admin/service/ProcessService.java
  src/main/java/beyond/samdasoo/admin/service/ProcessServiceImpl.java
  src/main/java/beyond/samdasoo/admin/service/SubProcessService.java
  src/main/java/beyond/samdasoo/admin/service/SubProcessServiceImpl.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
Labels: backend, feat

#44 [Proposal/#10] 제안 수정, 삭제, 모든 조회 API 추가 및 BaseResponse<List<>> 업데이트
  src/main/java/beyond/samdasoo/proposal/controller/ProposalController.java
  src/main/java/beyond/samdasoo/proposal/entity/Proposal.java
  src/main/java/beyond/samdasoo/proposal/repository/ProposalRepository.java
  src/main/java/beyond/samdasoo/proposal/service/ProposalService.java
Labels: backend, feat

#45 [Process/#31] 프로세스/하위 프로세스 수정/삭제 api 추가
  src/main/java/beyond/samdasoo/admin/controller/ProcessController.java
  src/main/java/beyond/samdasoo/admin/controller/SubProcessController.java
  src/main/java/beyond/samdasoo/admin/dto/SubProcessRequestDto.java
  src/main/java/beyond/samdasoo/admin/service/ProcessService.java
  src/main/java/beyond/samdasoo/admin/service/ProcessServiceImpl.java
  src/main/java/beyond/samdasoo/admin/service/SubProcessService.java
  src/main/java/beyond/samdasoo/admin/service/SubProcessServiceImpl.java
  src/main/java/beyond/samdasoo/common/response/BaseResponseStatus.java
Labels: backend, feat
